package com.pavlova.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Computed metrics for a feed session.
 * Generated by the drift analysis engine after content classification.
 */
@Entity(
    tableName = "session_metrics",
    foreignKeys = [
        ForeignKey(
            entity = FeedSession::class,
            parentColumns = ["id"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("sessionId")]
)
data class SessionMetrics(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    val sessionId: String,
    val computedAt: Long = System.currentTimeMillis(),

    // --- Diversity Metrics ---

    /** Shannon entropy of topic distribution. Higher = more diverse. */
    val topicEntropy: Float = 0f,

    /** Shannon entropy of creator distribution. Higher = more creators. */
    val creatorEntropy: Float = 0f,

    /** Number of distinct topics in the session */
    val uniqueTopics: Int = 0,

    /** Number of distinct creators in the session */
    val uniqueCreators: Int = 0,

    // --- Emotional Metrics ---

    /** Average sentiment score across all items */
    val avgSentiment: Float = 0f,

    /** Sentiment variance (low = monotone emotional tone) */
    val sentimentVariance: Float = 0f,

    /** Average toxicity across all items */
    val avgToxicity: Float = 0f,

    /** Average persuasion score across all items */
    val avgPersuasion: Float = 0f,

    /** Whether emotional intensity increases over the session */
    val emotionalEscalation: Float = 0f,

    // --- Concentration Metrics ---

    /** Gini coefficient of creator exposure (0=equal, 1=one creator dominates) */
    val creatorConcentration: Float = 0f,

    /** Fraction of items from the single most common topic */
    val topTopicShare: Float = 0f,

    // --- Manipulation Indicators ---

    /** Overall manipulation risk score: 0.0 (no concern) to 1.0 (high risk) */
    val manipulationScore: Float = 0f,

    /** JSON-encoded map of indicator names to scores for explainability */
    val indicatorBreakdown: String? = null
)
